services:
  mongo1:
    image: mongo:8.0
    container_name: mongo1
    hostname: mongo1
    mem_limit: 2200m
    volumes:
      - ../Docker_single/init:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    networks:
       - infrastructure
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=facility_rental
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7
    container_name: redis
    hostname: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - infrastructure
    expose:
      - "6379"

    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 20s
      timeout: 5s
      retries: 5

  backend:
    image: kacpermaziarz/facility_rental:0.0.1
    container_name: backend
    hostname: backend
    networks:
      - infrastructure
    expose:
      - "8080"

    depends_on:
      - mongo1
      - redis

  nginx:
    image: kacpermaziarz/facility_rental_nginx:0.0.1
    container_name: nginx
    mem_limit: 128m


    ports:
      - "20217:80"
    hostname: nginx
    depends_on:
        - backend
    restart: unless-stopped
    networks:
      - infrastructure
      - dmz



volumes:
  redis_data:

  mongo_data:


networks:
  infrastructure:
    internal: true
  dmz:
    internal: false
